version: '3'
services:
  lb:
    image: nginx:1.13-alpine
    depends_on:
      - web
      - api-web
    ports:
      - "8080:80"
    volumes:
      - ./lb-nginx.conf:/etc/nginx/nginx.conf
  web:
    image: search2d/web
  api-web:
    image: search2d/api-web
    depends_on:
      - api-php
    environment:
      - PHP_HOST
      - PHP_PORT
  api-php:
    image: search2d/api-php
    depends_on:
      - db
      - flb
    environment:
      - API_DATABASE_DSN
      - API_LOGGER_NAME
      - API_LOGGER_STREAM_ENABLED
      - API_LOGGER_STREAM_PATH
      - API_LOGGER_STREAM_LEVEL
      - API_LOGGER_FLUENT_ENABLED
      - API_LOGGER_FLUENT_TAG
      - API_LOGGER_FLUENT_HOST
      - API_LOGGER_FLUENT_PORT
      - API_LOGGER_FLUENT_LEVEL
      - API_LOGGER_FLUENT_UID_PATH
      - API_LOGGER_FLUENT_LOG_GROUP_NAME
      - API_ROUTER_CACHE_FILE
      - API_ROUTER_CACHE_DISABLED
      - API_SEARCH_S3_REGION
      - API_SEARCH_S3_INDEXED_IMAGE_BUCKET
      - API_SEARCH_S3_INDEXED_IMAGE_BASE_URL
      - API_SEARCH_S3_QUERIED_IMAGE_BUCKET
      - API_SEARCH_S3_QUERIED_IMAGE_BASE_URL
      - API_SEARCH_NNS_BASE_URI
      - API_PIXIV_API_USERNAME
      - API_PIXIV_API_PASSWORD
      - API_PIXIV_API_CLIENT_ID
      - API_PIXIV_API_CLIENT_SECRET
      - API_PIXIV_API_PROXY
      - API_PIXIV_SQS_REGION
      - API_PIXIV_SQS_REQUEST_ILLUST_URL
      - API_PIXIV_SQS_REQUEST_RANKING_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  nns:
    image: search2d/nns
    depends_on:
      - db
    environment:
      - NNS_ADDR
      - NNS_DSN
      - NNS_INDEXED_IMAGE_BUCKET
      - NNS_QUERIED_IMAGE_BUCKET
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD
  flb:
    image: search2d/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY